export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const OFFLINE = "OFFLINE";

export const GET_ITEM_DATA = "GET_ITEM_DATA";
export const GET_CHARACTER_DATA = "GET_CHARACTER_DATA";
export const GET_WEAPON_DATA = "GET_WEAPON_DATA";
export const GET_USERITEM_DATA = "GET_USERITEM_DATA";
export const GET_USERCHARACTER_DATA = "GET_USERCHARACTER_DATA";
export const GET_USERWEAPON_DATA = "GET_USERWEAPON_DATA";
export const UPDATE_USERWEAPON_DATA = "UPDATE_USERWEAPON_DATA";

export const GET_ITEM_DATA_FAIL = "GET_ITEM_DATA_FAIL";
export const GET_CHARACTER_DATA_FAIL = "GET_CHARACTER_DATA_FAIL";
export const GET_WEAPON_DATA_FAIL = "GET_WEAPON_DATA_FAIL";
export const GET_USERITEM_DATA_FAIL = "GET_USERITEM_DATA_FAIL";
export const GET_USERCHARACTER_DATA_FAIL = "GET_USERCHARACTER_DATA_FAIL";
export const GET_USERWEAPON_DATA_FAIL = "GET_USERWEAPON_DATA_FAIL";
export const UPDATE_USERCHARACTER_DATA = "GET_USERCHARACTER_DATA";
export const UPDATE_CHARACTER_DATA = "UPDATE_CHARACTER_DATA";