export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_LOGIN_INFO = "SET_LOGIN_INFO";

export const GET_ITEM_DATA = "GET_ITEM_DATA";
export const GET_CHARACTER_DATA = "GET_CHARACTER_DATA";
export const GET_WEAPON_DATA = "GET_WEAPON_DATA";
export const GET_USERITEM_DATA = "GET_USERITEM_DATA";
export const GET_USERCHARACTER_DATA = "GET_USERCHARACTER_DATA";
export const GET_USERWEAPON_DATA = "GET_USERWEAPON_DATA";